version: '3.8'

services:
  grobid-server:
    image: grobid/grobid:0.8.0
    container_name: grobid-server
    ports:
      - 8070:8070
      - 8071:8071
    volumes:
      - ./config/grobid:/home/config/grobid
    restart: always
      
  grobid-client:
    image: jorgesaenzdemiera/grobid_pdf:v3
    container_name: grobid-client
    volumes:
      - ./input:/input
      - ./output:/output
    
    depends_on:
      - grobid-server


networks:
  default:
    driver: bridge  