version: '3.8'

services:
  grobid-server:
    image: grobid/grobid:0.8.0
    container_name: grobid-server
    ports:
      - 8070:8070
      - 8071:8071
    volumes:
      - ./config/grobid:/home/config/grobid
    restart: always
      
  paper_analysis:
    image: jorgesaenzdemiera/grobid_pdf:latest
    container_name: grobid-client
    volumes:
      - ./input:/home/input
      - ./output:/home/output
    
    depends_on:
      - grobid-server

    restart: always

networks:
  default:
    driver: bridge  